#!/usr/bin/env python3
"""
Generate a Civic House kit for a city/country. Copies templates + ops into civic-houses/kits/<city>-<country>/.
Usage: python generate_civic_house_kit.py CITY COUNTRY [--overrides PATH]
Example: python generate_civic_house_kit.py Miami USA
"""
import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = REPO_ROOT / "civic-houses" / "templates"
OPS_DIR = REPO_ROOT / "civic-houses" / "ops"
SPEC_DIR = REPO_ROOT / "civic-houses" / "spec"
KITS_DIR = REPO_ROOT / "civic-houses" / "kits"


def slug(s: str) -> str:
    return s.strip().replace(" ", "-").replace("á", "a").replace("é", "e").replace("í", "i").replace("ó", "o").replace("ú", "u")


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate Civic House kit for city/country")
    ap.add_argument("city", help="City name (e.g. Miami)")
    ap.add_argument("country", help="Country name or code (e.g. USA)")
    ap.add_argument("--overrides", type=Path, help="Optional path to overrides file (not implemented yet)")
    args = ap.parse_args()
    city_slug = slug(args.city)
    country_slug = slug(args.country)
    kit_name = f"{city_slug}-{country_slug}"
    out_dir = KITS_DIR / kit_name
    if out_dir.exists():
        print(f"Kit already exists: {out_dir}", file=sys.stderr)
        sys.exit(1)
    out_dir.mkdir(parents=True)
    (out_dir / "brand.md").write_text(
        f"# Civic House — {args.city}, {args.country}\n\n"
        "Diaspora civic infrastructure — services, credentials, coordination. Complementary to host-state; no representation claims.\n"
        "See templates for full brand and ops.\n"
    )
    for f in TEMPLATES_DIR.glob("*.md"):
        shutil.copy2(f, out_dir / f.name)
    ops_sub = out_dir / "ops"
    ops_sub.mkdir()
    for f in OPS_DIR.glob("*.md"):
        shutil.copy2(f, ops_sub / f.name)
    spec_sub = out_dir / "spec"
    spec_sub.mkdir()
    if (SPEC_DIR / "credentialing_v0.md").exists():
        shutil.copy2(SPEC_DIR / "credentialing_v0.md", spec_sub / "credentialing_v0.md")
    (out_dir / "README.md").write_text(
        f"# Civic House kit — {args.city}, {args.country}\n\n"
        f"Generated by scripts/generate_civic_house_kit.py. Customize brand.md, service_catalog, events_playbook, and ops/ as needed.\n"
    )
    print(f"Generated: {out_dir}")


if __name__ == "__main__":
    main()
